// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionServiceClient interface {
	GetPublicKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PublicKeyResponse, error)
	ChangeModeRestart(ctx context.Context, in *OperationMode, opts ...grpc.CallOption) (*Empty, error)
	FailureCommand(ctx context.Context, in *FailureCommandMode, opts ...grpc.CallOption) (*Empty, error)
	StopAndGetProfilingResult(ctx context.Context, in *Profiling, opts ...grpc.CallOption) (TransactionService_StopAndGetProfilingResultClient, error)
	ProcessProposalOrderlessChainStream(ctx context.Context, opts ...grpc.CallOption) (TransactionService_ProcessProposalOrderlessChainStreamClient, error)
	CommitOrderlessChainTransactionStream(ctx context.Context, opts ...grpc.CallOption) (TransactionService_CommitOrderlessChainTransactionStreamClient, error)
	ProcessProposalFabricStream(ctx context.Context, opts ...grpc.CallOption) (TransactionService_ProcessProposalFabricStreamClient, error)
	ProcessProposalFabricCRDTStream(ctx context.Context, opts ...grpc.CallOption) (TransactionService_ProcessProposalFabricCRDTStreamClient, error)
	SubscribeProposalResponse(ctx context.Context, in *ProposalResponseEventSubscription, opts ...grpc.CallOption) (TransactionService_SubscribeProposalResponseClient, error)
	SubscribeTransactionResponse(ctx context.Context, in *TransactionResponseEventSubscription, opts ...grpc.CallOption) (TransactionService_SubscribeTransactionResponseClient, error)
	SubscribeNodeTransactions(ctx context.Context, in *TransactionResponseEventSubscription, opts ...grpc.CallOption) (TransactionService_SubscribeNodeTransactionsClient, error)
	SubscribeBlocksSyncHotStuff(ctx context.Context, in *BlockEventSubscription, opts ...grpc.CallOption) (TransactionService_SubscribeBlocksSyncHotStuffClient, error)
	AddClientPublicKey(ctx context.Context, in *TransactionResponseEventSubscription, opts ...grpc.CallOption) (*Empty, error)
	GetTransactionProfilingResult(ctx context.Context, in *Empty, opts ...grpc.CallOption) (TransactionService_GetTransactionProfilingResultClient, error)
	GetCPUMemoryProfilingResult(ctx context.Context, in *Empty, opts ...grpc.CallOption) (TransactionService_GetCPUMemoryProfilingResultClient, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) GetPublicKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	out := new(PublicKeyResponse)
	err := c.cc.Invoke(ctx, "/protos.TransactionService/GetPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) ChangeModeRestart(ctx context.Context, in *OperationMode, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.TransactionService/ChangeModeRestart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) FailureCommand(ctx context.Context, in *FailureCommandMode, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.TransactionService/FailureCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) StopAndGetProfilingResult(ctx context.Context, in *Profiling, opts ...grpc.CallOption) (TransactionService_StopAndGetProfilingResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[0], "/protos.TransactionService/StopAndGetProfilingResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceStopAndGetProfilingResultClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionService_StopAndGetProfilingResultClient interface {
	Recv() (*ProfilingResult, error)
	grpc.ClientStream
}

type transactionServiceStopAndGetProfilingResultClient struct {
	grpc.ClientStream
}

func (x *transactionServiceStopAndGetProfilingResultClient) Recv() (*ProfilingResult, error) {
	m := new(ProfilingResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) ProcessProposalOrderlessChainStream(ctx context.Context, opts ...grpc.CallOption) (TransactionService_ProcessProposalOrderlessChainStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[1], "/protos.TransactionService/ProcessProposalOrderlessChainStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceProcessProposalOrderlessChainStreamClient{stream}
	return x, nil
}

type TransactionService_ProcessProposalOrderlessChainStreamClient interface {
	Send(*ProposalRequest) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type transactionServiceProcessProposalOrderlessChainStreamClient struct {
	grpc.ClientStream
}

func (x *transactionServiceProcessProposalOrderlessChainStreamClient) Send(m *ProposalRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transactionServiceProcessProposalOrderlessChainStreamClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) CommitOrderlessChainTransactionStream(ctx context.Context, opts ...grpc.CallOption) (TransactionService_CommitOrderlessChainTransactionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[2], "/protos.TransactionService/CommitOrderlessChainTransactionStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceCommitOrderlessChainTransactionStreamClient{stream}
	return x, nil
}

type TransactionService_CommitOrderlessChainTransactionStreamClient interface {
	Send(*Transaction) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type transactionServiceCommitOrderlessChainTransactionStreamClient struct {
	grpc.ClientStream
}

func (x *transactionServiceCommitOrderlessChainTransactionStreamClient) Send(m *Transaction) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transactionServiceCommitOrderlessChainTransactionStreamClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) ProcessProposalFabricStream(ctx context.Context, opts ...grpc.CallOption) (TransactionService_ProcessProposalFabricStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[3], "/protos.TransactionService/ProcessProposalFabricStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceProcessProposalFabricStreamClient{stream}
	return x, nil
}

type TransactionService_ProcessProposalFabricStreamClient interface {
	Send(*ProposalRequest) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type transactionServiceProcessProposalFabricStreamClient struct {
	grpc.ClientStream
}

func (x *transactionServiceProcessProposalFabricStreamClient) Send(m *ProposalRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transactionServiceProcessProposalFabricStreamClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) ProcessProposalFabricCRDTStream(ctx context.Context, opts ...grpc.CallOption) (TransactionService_ProcessProposalFabricCRDTStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[4], "/protos.TransactionService/ProcessProposalFabricCRDTStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceProcessProposalFabricCRDTStreamClient{stream}
	return x, nil
}

type TransactionService_ProcessProposalFabricCRDTStreamClient interface {
	Send(*ProposalRequest) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type transactionServiceProcessProposalFabricCRDTStreamClient struct {
	grpc.ClientStream
}

func (x *transactionServiceProcessProposalFabricCRDTStreamClient) Send(m *ProposalRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transactionServiceProcessProposalFabricCRDTStreamClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) SubscribeProposalResponse(ctx context.Context, in *ProposalResponseEventSubscription, opts ...grpc.CallOption) (TransactionService_SubscribeProposalResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[5], "/protos.TransactionService/SubscribeProposalResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceSubscribeProposalResponseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionService_SubscribeProposalResponseClient interface {
	Recv() (*ProposalResponse, error)
	grpc.ClientStream
}

type transactionServiceSubscribeProposalResponseClient struct {
	grpc.ClientStream
}

func (x *transactionServiceSubscribeProposalResponseClient) Recv() (*ProposalResponse, error) {
	m := new(ProposalResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) SubscribeTransactionResponse(ctx context.Context, in *TransactionResponseEventSubscription, opts ...grpc.CallOption) (TransactionService_SubscribeTransactionResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[6], "/protos.TransactionService/SubscribeTransactionResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceSubscribeTransactionResponseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionService_SubscribeTransactionResponseClient interface {
	Recv() (*TransactionResponse, error)
	grpc.ClientStream
}

type transactionServiceSubscribeTransactionResponseClient struct {
	grpc.ClientStream
}

func (x *transactionServiceSubscribeTransactionResponseClient) Recv() (*TransactionResponse, error) {
	m := new(TransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) SubscribeNodeTransactions(ctx context.Context, in *TransactionResponseEventSubscription, opts ...grpc.CallOption) (TransactionService_SubscribeNodeTransactionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[7], "/protos.TransactionService/SubscribeNodeTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceSubscribeNodeTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionService_SubscribeNodeTransactionsClient interface {
	Recv() (*NodeTransactionResponse, error)
	grpc.ClientStream
}

type transactionServiceSubscribeNodeTransactionsClient struct {
	grpc.ClientStream
}

func (x *transactionServiceSubscribeNodeTransactionsClient) Recv() (*NodeTransactionResponse, error) {
	m := new(NodeTransactionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) SubscribeBlocksSyncHotStuff(ctx context.Context, in *BlockEventSubscription, opts ...grpc.CallOption) (TransactionService_SubscribeBlocksSyncHotStuffClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[8], "/protos.TransactionService/SubscribeBlocksSyncHotStuff", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceSubscribeBlocksSyncHotStuffClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionService_SubscribeBlocksSyncHotStuffClient interface {
	Recv() (*Block, error)
	grpc.ClientStream
}

type transactionServiceSubscribeBlocksSyncHotStuffClient struct {
	grpc.ClientStream
}

func (x *transactionServiceSubscribeBlocksSyncHotStuffClient) Recv() (*Block, error) {
	m := new(Block)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) AddClientPublicKey(ctx context.Context, in *TransactionResponseEventSubscription, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.TransactionService/AddClientPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransactionProfilingResult(ctx context.Context, in *Empty, opts ...grpc.CallOption) (TransactionService_GetTransactionProfilingResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[9], "/protos.TransactionService/GetTransactionProfilingResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceGetTransactionProfilingResultClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionService_GetTransactionProfilingResultClient interface {
	Recv() (*LatencyBreakDown, error)
	grpc.ClientStream
}

type transactionServiceGetTransactionProfilingResultClient struct {
	grpc.ClientStream
}

func (x *transactionServiceGetTransactionProfilingResultClient) Recv() (*LatencyBreakDown, error) {
	m := new(LatencyBreakDown)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *transactionServiceClient) GetCPUMemoryProfilingResult(ctx context.Context, in *Empty, opts ...grpc.CallOption) (TransactionService_GetCPUMemoryProfilingResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &TransactionService_ServiceDesc.Streams[10], "/protos.TransactionService/GetCPUMemoryProfilingResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &transactionServiceGetCPUMemoryProfilingResultClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TransactionService_GetCPUMemoryProfilingResultClient interface {
	Recv() (*MemoryCPUProfile, error)
	grpc.ClientStream
}

type transactionServiceGetCPUMemoryProfilingResultClient struct {
	grpc.ClientStream
}

func (x *transactionServiceGetCPUMemoryProfilingResultClient) Recv() (*MemoryCPUProfile, error) {
	m := new(MemoryCPUProfile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransactionServiceServer is the server API for TransactionService service.
// All implementations should embed UnimplementedTransactionServiceServer
// for forward compatibility
type TransactionServiceServer interface {
	GetPublicKey(context.Context, *Empty) (*PublicKeyResponse, error)
	ChangeModeRestart(context.Context, *OperationMode) (*Empty, error)
	FailureCommand(context.Context, *FailureCommandMode) (*Empty, error)
	StopAndGetProfilingResult(*Profiling, TransactionService_StopAndGetProfilingResultServer) error
	ProcessProposalOrderlessChainStream(TransactionService_ProcessProposalOrderlessChainStreamServer) error
	CommitOrderlessChainTransactionStream(TransactionService_CommitOrderlessChainTransactionStreamServer) error
	ProcessProposalFabricStream(TransactionService_ProcessProposalFabricStreamServer) error
	ProcessProposalFabricCRDTStream(TransactionService_ProcessProposalFabricCRDTStreamServer) error
	SubscribeProposalResponse(*ProposalResponseEventSubscription, TransactionService_SubscribeProposalResponseServer) error
	SubscribeTransactionResponse(*TransactionResponseEventSubscription, TransactionService_SubscribeTransactionResponseServer) error
	SubscribeNodeTransactions(*TransactionResponseEventSubscription, TransactionService_SubscribeNodeTransactionsServer) error
	SubscribeBlocksSyncHotStuff(*BlockEventSubscription, TransactionService_SubscribeBlocksSyncHotStuffServer) error
	AddClientPublicKey(context.Context, *TransactionResponseEventSubscription) (*Empty, error)
	GetTransactionProfilingResult(*Empty, TransactionService_GetTransactionProfilingResultServer) error
	GetCPUMemoryProfilingResult(*Empty, TransactionService_GetCPUMemoryProfilingResultServer) error
}

// UnimplementedTransactionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (UnimplementedTransactionServiceServer) GetPublicKey(context.Context, *Empty) (*PublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedTransactionServiceServer) ChangeModeRestart(context.Context, *OperationMode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeModeRestart not implemented")
}
func (UnimplementedTransactionServiceServer) FailureCommand(context.Context, *FailureCommandMode) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailureCommand not implemented")
}
func (UnimplementedTransactionServiceServer) StopAndGetProfilingResult(*Profiling, TransactionService_StopAndGetProfilingResultServer) error {
	return status.Errorf(codes.Unimplemented, "method StopAndGetProfilingResult not implemented")
}
func (UnimplementedTransactionServiceServer) ProcessProposalOrderlessChainStream(TransactionService_ProcessProposalOrderlessChainStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessProposalOrderlessChainStream not implemented")
}
func (UnimplementedTransactionServiceServer) CommitOrderlessChainTransactionStream(TransactionService_CommitOrderlessChainTransactionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CommitOrderlessChainTransactionStream not implemented")
}
func (UnimplementedTransactionServiceServer) ProcessProposalFabricStream(TransactionService_ProcessProposalFabricStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessProposalFabricStream not implemented")
}
func (UnimplementedTransactionServiceServer) ProcessProposalFabricCRDTStream(TransactionService_ProcessProposalFabricCRDTStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessProposalFabricCRDTStream not implemented")
}
func (UnimplementedTransactionServiceServer) SubscribeProposalResponse(*ProposalResponseEventSubscription, TransactionService_SubscribeProposalResponseServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeProposalResponse not implemented")
}
func (UnimplementedTransactionServiceServer) SubscribeTransactionResponse(*TransactionResponseEventSubscription, TransactionService_SubscribeTransactionResponseServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTransactionResponse not implemented")
}
func (UnimplementedTransactionServiceServer) SubscribeNodeTransactions(*TransactionResponseEventSubscription, TransactionService_SubscribeNodeTransactionsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeNodeTransactions not implemented")
}
func (UnimplementedTransactionServiceServer) SubscribeBlocksSyncHotStuff(*BlockEventSubscription, TransactionService_SubscribeBlocksSyncHotStuffServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeBlocksSyncHotStuff not implemented")
}
func (UnimplementedTransactionServiceServer) AddClientPublicKey(context.Context, *TransactionResponseEventSubscription) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddClientPublicKey not implemented")
}
func (UnimplementedTransactionServiceServer) GetTransactionProfilingResult(*Empty, TransactionService_GetTransactionProfilingResultServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTransactionProfilingResult not implemented")
}
func (UnimplementedTransactionServiceServer) GetCPUMemoryProfilingResult(*Empty, TransactionService_GetCPUMemoryProfilingResultServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCPUMemoryProfilingResult not implemented")
}

// UnsafeTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServiceServer will
// result in compilation errors.
type UnsafeTransactionServiceServer interface {
	mustEmbedUnimplementedTransactionServiceServer()
}

func RegisterTransactionServiceServer(s grpc.ServiceRegistrar, srv TransactionServiceServer) {
	s.RegisterService(&TransactionService_ServiceDesc, srv)
}

func _TransactionService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.TransactionService/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetPublicKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_ChangeModeRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationMode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).ChangeModeRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.TransactionService/ChangeModeRestart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).ChangeModeRestart(ctx, req.(*OperationMode))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_FailureCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailureCommandMode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).FailureCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.TransactionService/FailureCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).FailureCommand(ctx, req.(*FailureCommandMode))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_StopAndGetProfilingResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Profiling)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionServiceServer).StopAndGetProfilingResult(m, &transactionServiceStopAndGetProfilingResultServer{stream})
}

type TransactionService_StopAndGetProfilingResultServer interface {
	Send(*ProfilingResult) error
	grpc.ServerStream
}

type transactionServiceStopAndGetProfilingResultServer struct {
	grpc.ServerStream
}

func (x *transactionServiceStopAndGetProfilingResultServer) Send(m *ProfilingResult) error {
	return x.ServerStream.SendMsg(m)
}

func _TransactionService_ProcessProposalOrderlessChainStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionServiceServer).ProcessProposalOrderlessChainStream(&transactionServiceProcessProposalOrderlessChainStreamServer{stream})
}

type TransactionService_ProcessProposalOrderlessChainStreamServer interface {
	SendAndClose(*Empty) error
	Recv() (*ProposalRequest, error)
	grpc.ServerStream
}

type transactionServiceProcessProposalOrderlessChainStreamServer struct {
	grpc.ServerStream
}

func (x *transactionServiceProcessProposalOrderlessChainStreamServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transactionServiceProcessProposalOrderlessChainStreamServer) Recv() (*ProposalRequest, error) {
	m := new(ProposalRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TransactionService_CommitOrderlessChainTransactionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionServiceServer).CommitOrderlessChainTransactionStream(&transactionServiceCommitOrderlessChainTransactionStreamServer{stream})
}

type TransactionService_CommitOrderlessChainTransactionStreamServer interface {
	SendAndClose(*Empty) error
	Recv() (*Transaction, error)
	grpc.ServerStream
}

type transactionServiceCommitOrderlessChainTransactionStreamServer struct {
	grpc.ServerStream
}

func (x *transactionServiceCommitOrderlessChainTransactionStreamServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transactionServiceCommitOrderlessChainTransactionStreamServer) Recv() (*Transaction, error) {
	m := new(Transaction)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TransactionService_ProcessProposalFabricStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionServiceServer).ProcessProposalFabricStream(&transactionServiceProcessProposalFabricStreamServer{stream})
}

type TransactionService_ProcessProposalFabricStreamServer interface {
	SendAndClose(*Empty) error
	Recv() (*ProposalRequest, error)
	grpc.ServerStream
}

type transactionServiceProcessProposalFabricStreamServer struct {
	grpc.ServerStream
}

func (x *transactionServiceProcessProposalFabricStreamServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transactionServiceProcessProposalFabricStreamServer) Recv() (*ProposalRequest, error) {
	m := new(ProposalRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TransactionService_ProcessProposalFabricCRDTStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransactionServiceServer).ProcessProposalFabricCRDTStream(&transactionServiceProcessProposalFabricCRDTStreamServer{stream})
}

type TransactionService_ProcessProposalFabricCRDTStreamServer interface {
	SendAndClose(*Empty) error
	Recv() (*ProposalRequest, error)
	grpc.ServerStream
}

type transactionServiceProcessProposalFabricCRDTStreamServer struct {
	grpc.ServerStream
}

func (x *transactionServiceProcessProposalFabricCRDTStreamServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transactionServiceProcessProposalFabricCRDTStreamServer) Recv() (*ProposalRequest, error) {
	m := new(ProposalRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TransactionService_SubscribeProposalResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProposalResponseEventSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionServiceServer).SubscribeProposalResponse(m, &transactionServiceSubscribeProposalResponseServer{stream})
}

type TransactionService_SubscribeProposalResponseServer interface {
	Send(*ProposalResponse) error
	grpc.ServerStream
}

type transactionServiceSubscribeProposalResponseServer struct {
	grpc.ServerStream
}

func (x *transactionServiceSubscribeProposalResponseServer) Send(m *ProposalResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TransactionService_SubscribeTransactionResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransactionResponseEventSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionServiceServer).SubscribeTransactionResponse(m, &transactionServiceSubscribeTransactionResponseServer{stream})
}

type TransactionService_SubscribeTransactionResponseServer interface {
	Send(*TransactionResponse) error
	grpc.ServerStream
}

type transactionServiceSubscribeTransactionResponseServer struct {
	grpc.ServerStream
}

func (x *transactionServiceSubscribeTransactionResponseServer) Send(m *TransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TransactionService_SubscribeNodeTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransactionResponseEventSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionServiceServer).SubscribeNodeTransactions(m, &transactionServiceSubscribeNodeTransactionsServer{stream})
}

type TransactionService_SubscribeNodeTransactionsServer interface {
	Send(*NodeTransactionResponse) error
	grpc.ServerStream
}

type transactionServiceSubscribeNodeTransactionsServer struct {
	grpc.ServerStream
}

func (x *transactionServiceSubscribeNodeTransactionsServer) Send(m *NodeTransactionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TransactionService_SubscribeBlocksSyncHotStuff_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlockEventSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionServiceServer).SubscribeBlocksSyncHotStuff(m, &transactionServiceSubscribeBlocksSyncHotStuffServer{stream})
}

type TransactionService_SubscribeBlocksSyncHotStuffServer interface {
	Send(*Block) error
	grpc.ServerStream
}

type transactionServiceSubscribeBlocksSyncHotStuffServer struct {
	grpc.ServerStream
}

func (x *transactionServiceSubscribeBlocksSyncHotStuffServer) Send(m *Block) error {
	return x.ServerStream.SendMsg(m)
}

func _TransactionService_AddClientPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionResponseEventSubscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).AddClientPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.TransactionService/AddClientPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).AddClientPublicKey(ctx, req.(*TransactionResponseEventSubscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransactionProfilingResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionServiceServer).GetTransactionProfilingResult(m, &transactionServiceGetTransactionProfilingResultServer{stream})
}

type TransactionService_GetTransactionProfilingResultServer interface {
	Send(*LatencyBreakDown) error
	grpc.ServerStream
}

type transactionServiceGetTransactionProfilingResultServer struct {
	grpc.ServerStream
}

func (x *transactionServiceGetTransactionProfilingResultServer) Send(m *LatencyBreakDown) error {
	return x.ServerStream.SendMsg(m)
}

func _TransactionService_GetCPUMemoryProfilingResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransactionServiceServer).GetCPUMemoryProfilingResult(m, &transactionServiceGetCPUMemoryProfilingResultServer{stream})
}

type TransactionService_GetCPUMemoryProfilingResultServer interface {
	Send(*MemoryCPUProfile) error
	grpc.ServerStream
}

type transactionServiceGetCPUMemoryProfilingResultServer struct {
	grpc.ServerStream
}

func (x *transactionServiceGetCPUMemoryProfilingResultServer) Send(m *MemoryCPUProfile) error {
	return x.ServerStream.SendMsg(m)
}

// TransactionService_ServiceDesc is the grpc.ServiceDesc for TransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _TransactionService_GetPublicKey_Handler,
		},
		{
			MethodName: "ChangeModeRestart",
			Handler:    _TransactionService_ChangeModeRestart_Handler,
		},
		{
			MethodName: "FailureCommand",
			Handler:    _TransactionService_FailureCommand_Handler,
		},
		{
			MethodName: "AddClientPublicKey",
			Handler:    _TransactionService_AddClientPublicKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StopAndGetProfilingResult",
			Handler:       _TransactionService_StopAndGetProfilingResult_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProcessProposalOrderlessChainStream",
			Handler:       _TransactionService_ProcessProposalOrderlessChainStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CommitOrderlessChainTransactionStream",
			Handler:       _TransactionService_CommitOrderlessChainTransactionStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ProcessProposalFabricStream",
			Handler:       _TransactionService_ProcessProposalFabricStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ProcessProposalFabricCRDTStream",
			Handler:       _TransactionService_ProcessProposalFabricCRDTStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeProposalResponse",
			Handler:       _TransactionService_SubscribeProposalResponse_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTransactionResponse",
			Handler:       _TransactionService_SubscribeTransactionResponse_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeNodeTransactions",
			Handler:       _TransactionService_SubscribeNodeTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeBlocksSyncHotStuff",
			Handler:       _TransactionService_SubscribeBlocksSyncHotStuff_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTransactionProfilingResult",
			Handler:       _TransactionService_GetTransactionProfilingResult_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCPUMemoryProfilingResult",
			Handler:       _TransactionService_GetCPUMemoryProfilingResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "transaction.proto",
}
