---
- name: Deploying clients to the inventories
  hosts: clients
  tags: [ "deploy-clients" ]
  vars:
  tasks:
    - name: WAN network emulation delete
      command:
        cmd: "tc qdisc del dev {{ lookup('env', 'WAN_DRIVE') }} root netem"
      become: yes
      become_user: root
      ignore_errors: yes
    - pam_limits:
        domain: ubuntu
        limit_type: soft
        limit_item: nofile
        value: 64000
    - name: Stop clientchain
      ansible.builtin.service:
        name: clientchain
        state: stopped
      ignore_errors: yes
    - name: Delete all file in inventories
      file:
        state: absent
        path: "{{ lookup('env', 'REMOTE_CLIENT_PATH') }}"
    - name: Copy systemd service file to server
      copy:
        src: "{{ lookup('env', 'PROJECT_ABSOLUTE_PATH') }}/deployment/service/clientchain.service"
        dest: /etc/systemd/system
        owner: root
        group: root
    - name: Copy clients to inventories
      copy:
        src: "{{ lookup('env', 'PROJECT_ABSOLUTE_PATH') }}/{{ lookup('env', 'CLIENT_BUILD_PATH_LINUX') }}"
        dest: "{{ lookup('env', 'REMOTE_CLIENT_PATH') }}"
        mode: 0777
      become: yes
      become_user: "{{ lookup('env', 'REMOTE_USER') }}"
    - name: Copy Certs and Keys
      copy:
        src: "{{ lookup('env', 'PROJECT_ABSOLUTE_PATH') }}/certificates/{{ item.path }}/{{ inventory_hostname }}.pem"
        dest: "{{ lookup('env', 'REMOTE_CLIENT_PATH') }}configs/{{ item.type }}.pem"
      become: yes
      become_user: "{{ lookup('env', 'REMOTE_USER') }}"
      loop:
        - { type: key, path: keys }
        - { type: cert, path: certs }
    - name: Copy and unarchive Certs
      ansible.builtin.unarchive:
        src: "{{ lookup('env', 'PROJECT_ABSOLUTE_PATH') }}/certificates/certs.tgz"
        dest: "{{ lookup('env', 'REMOTE_CLIENT_PATH') }}configs/"
        mode: 0777
      become: yes
      become_user: "{{ lookup('env', 'REMOTE_USER') }}"
      notify:
        - Restart clientchain
    - name: WAN network emulation
      command:
        cmd: "tc qdisc add dev {{ lookup('env', 'WAN_DRIVE') }} root netem delay {{ lookup('env', 'WAN_DELAY') }}ms {{ lookup('env', 'WAN_JITTER') }}ms rate {{ lookup('env', 'WAN_RATE') }}kbit"
      become: yes
      become_user: root
      ignore_errors: yes
    - name: Start clientchain
      ansible.builtin.service:
        name: clientchain
        state: started
        enabled: yes
  handlers:
    - name: Restart clientchain
      ansible.builtin.service:
        name: clientchain
        state: restarted
