---
- name: Installing Go env for development on remote server
  hosts: clis
  tags: [ "install-go-env" ]
  vars:
    packages:
      - make
      - gcc
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
  roles:
    - role: gantsign.golang
      golang_version: "1.16.3"

#  ansible-galaxy install gantsign.golang
